# NumPy Indexing and Selecting

In [1]:
import numpy as np

## 1D Array

In [2]:
arr = np.arange(0,11)

In [3]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

### indexing 

In [6]:
arr[1:4]

array([1, 2, 3])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### value Broadcasting

In [10]:
arr[:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_arr = arr[:6]

In [22]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slice_arr[:] = 0

In [25]:
slice_arr

array([0, 0, 0, 0, 0, 0])

In [29]:
arr #incase of normal slicing the original value is changed,but this should be avoided by using copy method

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [31]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
copy_arr = arr.copy()
copy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
copy_arr[:] = 1000
copy_arr

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2D Array

In [37]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### indexing

In [41]:
arr_2d[0]

array([1, 2, 3])

In [38]:
arr_2d[:][0]

array([1, 2, 3])

In [40]:
arr_2d[2][1]

8

In [42]:
arr_2d[2,1]

8

In [43]:
arr_2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [44]:
arr_2d[1,:]

array([4, 5, 6])

In [45]:
arr_2d[:1,:3]

array([[1, 2, 3]])

### Selection

In [46]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[arr < 4]

array([1, 2, 3])

### 1D array to 2D array by reshape method

In [53]:
arr_2d = np.arange(25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr_2d[2,3]

13

In [55]:
arr_2d[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [56]:
arr_2d[2:,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])