# NumPy Arrays


In [1]:
my_list = [1,2,3,4,5]

In [2]:
my_list

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

### One Dimentional Array

In [6]:
arr =  np.array(my_list) #It will convert python_list to an array

In [5]:
arr

array([1, 2, 3, 4, 5])

### Two Dimentional Array 

In [7]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
m_arr = np.array(my_list2)

In [9]:
m_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange method

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2) #all even number between 0 to 11

array([ 0,  2,  4,  6,  8, 10])

### zeros method

In [12]:
np.zeros(5) #1D

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3)) #2D  (rows,columns)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ones method

In [14]:
np.ones(6) #1D

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((3,5)) #2D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace method

In [16]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Identity metrix with eye method

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

### random function

In [21]:
np.random.rand(5) #.rand(5) will create 5 random number between 0 to 1

array([0.15413351, 0.10986856, 0.93221059, 0.85958122, 0.94308779])

In [23]:
np.random.randint(1,20) #.randint for getting a random number between a range

8

In [24]:
np.random.randint(1,20,5)

array([ 3, 13,  3,  1, 18])

### reshape method

In [25]:
arr = np.random.randint(0,20,10)

In [26]:
arr

array([10,  1, 19, 10,  3,  7,  9, 12, 12,  1])

In [36]:
arr.shape

(10,)

In [39]:
arr = arr.reshape(2,5)

In [40]:
arr.shape

(2, 5)

In [41]:
arr = arr.reshape(5,2)

In [42]:
arr.shape

(5, 2)

In [29]:
arr.max() #to get max value of that array

19

In [30]:
arr.min() #to get min value of that array

1

In [31]:
arr.argmax() #for getting index location of max value

2

In [33]:
arr.argmin() #for getting index location of min value

1

In [45]:
arr.dtype #to get data type of that array

dtype('int32')

In [47]:
from numpy.random import randint

In [48]:
randint(50,100,10)

array([97, 84, 55, 60, 81, 52, 50, 50, 98, 85])